# Generated by Django 4.2.3 on 2023-07-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='tipo_cuenta',
            field=models.CharField(choices=[('AHORRO', 'ahorro'), ('CORRIENTE', 'corriente')], max_length=100),
        ),
    ]
